Ejercicios intervalo de confianza. Al igual que en el caso del ejercicio de la clase, piensa un motivo por el que sería interesante calcular estos intervalos de confianza para la extracción de insights.

Intervalo de Confianza para la Esperanza de Vida Contexto: Trabajas en una organización de salud global y deseas estimar el intervalo de confianza al 95% para la esperanza de vida promedio de cada continente. Nota: Cuidado porque puede que os salgan algunos nulos, genera un código para que no salgan nulos en los intervalos de confianza.

Intervalo de Confianza para el PIB Contexto: Eres una economista y quieres calcular el intervalo de confianza al 90% para el Producto Interno Bruto (PIB) de los continentes.

Prueba de Hipótesis

Test de Normalidad :Verifica si la variable "life_expectancy" (esperanza de vida) sigue una distribución normal usando el test de Shapiro-Wilk o Kolmogorov-Smirnov según el tamaño de la muestra.

Test de Igualdad de Varianzas: Comprueba si la varianza del PIB (GDP) es igual en países de Europa y África usando el test de Bartlett (si los datos son normales) o Levene (si no son normales).

Comparación de Medias (t-Test de Student o Mann-Whitney U): ¿La esperanza de vida difiere significativamente entre países de Europa y Asia?

Prueba de Hipótesis sobre Proporciones: ¿Hay una diferencia significativa en la tasa de desempleo entre los países de Europa y América?

Comparación de Medias en Precios de Gasolina : ¿El precio de la gasolina (gasoline_price) es significativamente diferente entre países con un PIB alto y PIB bajo?

In [1]:
# importamos las librerías que necesitamos

# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd

# Visualización
# ------------------------------------------------------------------------------
import matplotlib.pyplot as plt
import seaborn as sns

# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

In [2]:
import numpy as np
import warnings

In [2]:
# importamos las librerías que necesitamos
# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np
# Visualización
# ------------------------------------------------------------------------------
import matplotlib.pyplot as plt
import seaborn as sns
# Evaluar linealidad de las relaciones entre las variables
# ------------------------------------------------------------------------------
from scipy.stats import shapiro, kstest
# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames
# Gestión de los warnings
# -----------------------------------------------------------------------
import warnings
warnings.filterwarnings("ignore")

In [3]:
import scipy.stats as stats
from scipy.stats import shapiro, poisson, chisquare, expon, kstest

In [4]:
# lo primero que hacemos es cargar el dataframe que vamos a usar para esta lección
df = pd.read_csv("C:/Users/Usuario/Documents/Adalab49/Módulo 3/pair_mod3_Bea_Male/world_data_full_apply_nulos.csv", index_col=0) 

df.head(10)

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,cpi,cpi_change,currency-code,fertility_rate,forested_area,gasoline_price,gdp,gross_primary_education_enrollment,gross_tertiary_education_enrollment,infant_mortality,largest_city,life_expectancy,maternal_mortality_ratio,minimum_wage,official_language,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,latitude,longitude,continent
0,Afghanistan,60.0,AF,58.1,652.230,323.0,32.49,93.0,Kabul,8.672,149.90,2.3,AFN,4.47,2.1,0.70,1.910135e+10,104.0,9.7,47.9,Kabul,64.5,638.0,0.43,Pashto,78.4,0.28,NaN,48.9,9.3,71.4,11.12,NaN,33.939110,67.709953,Asia
1,Albania,105.0,AL,43.1,28.748,9.0,11.78,355.0,Tirana,4.536,119.05,1.4,ALL,1.62,28.1,1.36,1.527808e+10,107.0,55.0,7.8,Tirana,78.5,15.0,1.12,Albanian,56.9,1.20,NaN,55.7,18.6,36.6,12.33,NaN,41.153332,20.168331,Europe
2,Algeria,18.0,DZ,17.4,NaN,317.0,24.28,213.0,Algiers,150.006,151.36,2.0,DZD,3.02,0.8,0.28,1.699882e+11,109.9,51.4,20.1,Algiers,76.7,112.0,0.95,Arabic,28.1,1.72,NaN,41.2,37.2,66.1,11.70,NaN,28.033886,1.659626,Africa
3,Andorra,164.0,AD,40.0,468.000,NaN,7.20,376.0,Andorra la Vella,469.000,NaN,NaN,EUR,1.27,34.0,1.51,3.154058e+09,106.4,NaN,2.7,Andorra la Vella,NaN,NaN,6.63,Catalan,36.4,3.33,77.142,NaN,NaN,NaN,NaN,67.873,42.506285,1.521801,Europe
4,Angola,26.0,AO,47.5,NaN,117.0,40.73,244.0,Luanda,34.693,261.73,17.1,AOA,5.52,46.3,0.97,9.463542e+10,113.5,9.3,51.6,Luanda,60.8,241.0,0.71,Portuguese,33.4,0.21,NaN,77.5,9.2,49.1,6.89,NaN,-11.202692,17.873887,Africa
5,Antigua and Barbuda,223.0,AG,20.5,443.000,0.0,15.33,1.0,"St. John's, Saint John",557.000,113.81,1.2,XCD,1.99,22.3,0.99,1.727759e+09,105.0,24.8,5.0,"St. John's, Saint John",76.9,42.0,3.04,English,24.3,2.76,97.118,NaN,16.5,43.0,NaN,23.800,17.060816,-61.796428,Central America
6,Argentina,17.0,AR,54.3,NaN,105.0,17.02,54.0,Buenos Aires,201.348,232.75,53.5,ARS,2.26,9.8,1.10,4.496634e+11,109.7,90.0,8.8,Buenos Aires,76.5,39.0,3.35,Spanish,17.6,3.96,NaN,61.3,10.1,106.3,9.79,NaN,-38.416097,-63.616672,South America
7,Armenia,104.0,AM,58.9,29.743,49.0,13.99,374.0,Yerevan,5.156,129.18,1.4,AMD,1.76,11.7,0.77,1.367280e+10,92.7,54.6,11.0,Yerevan,74.9,26.0,0.66,Armenian,81.6,4.40,NaN,55.6,20.9,22.6,16.99,NaN,40.069099,45.038189,Asia
8,Australia,3.0,AU,48.2,NaN,58.0,12.60,61.0,Canberra,375.908,119.80,1.6,AUD,1.74,16.3,0.93,1.392681e+12,100.3,113.1,3.1,Sydney,82.7,6.0,13.59,NaN,19.6,3.68,NaN,65.5,23.0,47.4,5.27,NaN,-25.274398,133.775136,Oceania
9,Austria,109.0,AT,32.4,83.871,21.0,9.70,43.0,Vienna,61.448,118.06,1.5,EUR,1.47,46.9,1.20,4.463147e+11,103.1,85.1,2.9,Vienna,81.6,5.0,NaN,German,17.9,5.17,NaN,60.7,25.4,51.4,4.67,NaN,47.516231,14.550072,Europe

In [5]:
df.dropna()

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,cpi,cpi_change,currency-code,fertility_rate,forested_area,gasoline_price,gdp,gross_primary_education_enrollment,gross_tertiary_education_enrollment,infant_mortality,largest_city,life_expectancy,maternal_mortality_ratio,minimum_wage,official_language,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,latitude,longitude,continent
14,Barbados,668.00,BB,23.3,430.000,1.0,10.65,1.0,Bridgetown,1.276,134.09,4.1,BBD,1.62,14.7,1.81,5.209000e+09,99.4,65.4,11.3,Bridgetown,79.1,27.0,3.13,English,45.2,2.48,287.025,65.2,27.5,35.6,10.33,89.431,13.193887,-59.543198,Central America
17,Belize,17.00,BZ,7.0,22.966,2.0,20.79,501.0,Belmopan,568.000,105.68,-0.9,BZD,2.31,59.7,1.13,1.879614e+09,111.7,24.7,11.2,Belize City,74.5,36.0,1.65,English,22.7,1.12,390.353,65.1,26.3,31.1,6.41,179.039,17.189877,-88.497650,Central America
29,Cape Verde,138.00,CV,19.6,4.033,1.0,19.49,238.0,Praia,543.000,110.50,1.1,CVE,2.27,22.5,1.02,1.981846e+09,104.0,23.6,16.7,Praia,72.8,58.0,0.68,Portuguese,23.2,0.77,483.628,60.5,20.1,37.5,12.25,364.029,16.538800,-23.041800,Africa
58,Fiji,49.00,FJ,23.3,18.274,4.0,21.28,679.0,Suva,2.046,132.30,1.8,FJD,2.77,55.9,0.82,5.535549e+09,106.4,16.1,21.6,Suva,67.3,34.0,1.28,Fiji Hindi,21.4,0.84,889.953,57.6,24.2,32.1,4.10,505.048,-17.713371,178.065032,Oceania
100,Luxembourg,242.00,LU,53.7,2.586,2.0,10.30,352.0,Luxembourg City,8.988,115.09,1.7,EUR,1.37,35.7,1.19,7.110492e+10,102.3,19.2,1.9,Luxembourg City,82.1,5.0,13.05,Luxembourgish,10.6,3.01,645.397,59.3,26.5,20.4,5.36,565.488,49.815273,6.129583,Europe
106,Malta,1.38,MT,32.4,316.000,2.0,9.20,356.0,Valletta,1.342,113.45,1.6,EUR,1.23,1.1,1.36,1.478616e+10,105.0,54.3,6.1,Birkirkara,82.3,6.0,5.07,Maltese,37.1,2.86,502.653,56.5,26.2,44.0,3.47,475.902,35.937496,14.375416,Europe

In [8]:
df.isnull().sum()

country                                   0
density                                   0
abbreviation                              7
agricultural_land                         7
land_area                                30
armed_forces_size                        29
birth_rate                                6
calling_code                              1
capital/major_city                        3
co2-emissions                            12
cpi                                      20
cpi_change                               16
currency-code                            15
fertility_rate                            7
forested_area                             7
gasoline_price                           20
gdp                                       2
gross_primary_education_enrollment        7
gross_tertiary_education_enrollment      12
infant_mortality                          6
largest_city                              6
life_expectancy                           8
maternal_mortality_ratio                 14
minimum_wage                             45
official_language                         5
out_of_pocket_health_expenditure          7
physicians_per_thousand                   7
population                              156
population_labor_force_participation     19
tax_revenue                              26
total_tax_rate                           12
unemployment_rate                        19
urban_population                        150
latitude                                  1
longitude                                 1
continent                                 1
dtype: int64

In [9]:
df.dropna()

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,cpi,cpi_change,currency-code,fertility_rate,forested_area,gasoline_price,gdp,gross_primary_education_enrollment,gross_tertiary_education_enrollment,infant_mortality,largest_city,life_expectancy,maternal_mortality_ratio,minimum_wage,official_language,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,latitude,longitude,continent
14,Barbados,668.00,BB,23.3,430.000,1.0,10.65,1.0,Bridgetown,1.276,134.09,4.1,BBD,1.62,14.7,1.81,5.209000e+09,99.4,65.4,11.3,Bridgetown,79.1,27.0,3.13,English,45.2,2.48,287.025,65.2,27.5,35.6,10.33,89.431,13.193887,-59.543198,Central America
17,Belize,17.00,BZ,7.0,22.966,2.0,20.79,501.0,Belmopan,568.000,105.68,-0.9,BZD,2.31,59.7,1.13,1.879614e+09,111.7,24.7,11.2,Belize City,74.5,36.0,1.65,English,22.7,1.12,390.353,65.1,26.3,31.1,6.41,179.039,17.189877,-88.497650,Central America
29,Cape Verde,138.00,CV,19.6,4.033,1.0,19.49,238.0,Praia,543.000,110.50,1.1,CVE,2.27,22.5,1.02,1.981846e+09,104.0,23.6,16.7,Praia,72.8,58.0,0.68,Portuguese,23.2,0.77,483.628,60.5,20.1,37.5,12.25,364.029,16.538800,-23.041800,Africa
58,Fiji,49.00,FJ,23.3,18.274,4.0,21.28,679.0,Suva,2.046,132.30,1.8,FJD,2.77,55.9,0.82,5.535549e+09,106.4,16.1,21.6,Suva,67.3,34.0,1.28,Fiji Hindi,21.4,0.84,889.953,57.6,24.2,32.1,4.10,505.048,-17.713371,178.065032,Oceania
100,Luxembourg,242.00,LU,53.7,2.586,2.0,10.30,352.0,Luxembourg City,8.988,115.09,1.7,EUR,1.37,35.7,1.19,7.110492e+10,102.3,19.2,1.9,Luxembourg City,82.1,5.0,13.05,Luxembourgish,10.6,3.01,645.397,59.3,26.5,20.4,5.36,565.488,49.815273,6.129583,Europe
106,Malta,1.38,MT,32.4,316.000,2.0,9.20,356.0,Valletta,1.342,113.45,1.6,EUR,1.23,1.1,1.36,1.478616e+10,105.0,54.3,6.1,Birkirkara,82.3,6.0,5.07,Maltese,37.1,2.86,502.653,56.5,26.2,44.0,3.47,475.902,35.937496,14.375416,Europe

In [23]:
df=df.dropna()

In [24]:
df.isnull().sum()

country                                 0
density                                 0
abbreviation                            0
agricultural_land                       0
land_area                               0
armed_forces_size                       0
birth_rate                              0
calling_code                            0
capital/major_city                      0
co2-emissions                           0
cpi                                     0
cpi_change                              0
currency-code                           0
fertility_rate                          0
forested_area                           0
gasoline_price                          0
gdp                                     0
gross_primary_education_enrollment      0
gross_tertiary_education_enrollment     0
infant_mortality                        0
largest_city                            0
life_expectancy                         0
maternal_mortality_ratio                0
minimum_wage                            0
official_language                       0
out_of_pocket_health_expenditure        0
physicians_per_thousand                 0
population                              0
population_labor_force_participation    0
tax_revenue                             0
total_tax_rate                          0
unemployment_rate                       0
urban_population                        0
latitude                                0
longitude                               0
continent                               0
dtype: int64

In [19]:
df["continent"].info

<bound method Series.info of 14     Central America
17     Central America
29              Africa
58             Oceania
100             Europe
106             Europe
Name: continent, dtype: object>

In [27]:
for continent in df["life_expectancy"].unique():
    df_life = df[df["life_expectancy"] == continent]
    media = df_life["life_expectancy"].mean()
    error = stats.sem(df_life["life_expectancy"])
    grados_libertad = len(df_life["life_expectancy"])-1
    nivel_confianza = 0.95
    valor_critico = stats.t.ppf((1 + nivel_confianza) / 2, df=grados_libertad)
    salto = valor_critico * error
    limite_sup = media + salto
    limite_inf = media - salto
    print(continent)
    print(limite_inf, "-", limite_sup)
    print("---------------------------------------------------------")

79.1
nan - nan
---------------------------------------------------------
74.5
nan - nan
---------------------------------------------------------
72.8
nan - nan
---------------------------------------------------------
67.3
nan - nan
---------------------------------------------------------
82.1
nan - nan
---------------------------------------------------------
82.3
nan - nan
---------------------------------------------------------